# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loom < Formula
  desc "LLM memory: SQLite + BM25 + LLM, no embeddings."
  homepage "https://github.com/MatteoAdamo82/loom"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MatteoAdamo82/loom/releases/download/v0.4.0/loom_0.4.0_macos_x86_64.tar.gz"
      sha256 "24a52bc4eff7b94eb592dc317f1699e3b2f935986dc1ea247aeefff117169bed"

      define_method(:install) do
        bin.install "loom"
        bin.install "loom-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MatteoAdamo82/loom/releases/download/v0.4.0/loom_0.4.0_macos_arm64.tar.gz"
      sha256 "72e048b95a088e293990bfe0da1c237cf177b8c6817acd436650e5e928d1a9c5"

      define_method(:install) do
        bin.install "loom"
        bin.install "loom-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MatteoAdamo82/loom/releases/download/v0.4.0/loom_0.4.0_linux_x86_64.tar.gz"
      sha256 "55c4c95650c8bc398bb808e9fdbde7681828eb4eb9d612f4f78321fd78045318"
      define_method(:install) do
        bin.install "loom"
        bin.install "loom-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MatteoAdamo82/loom/releases/download/v0.4.0/loom_0.4.0_linux_arm64.tar.gz"
      sha256 "2fdeb92c60c698f8f277a2822b64ea6be6cec5a7b86b6fd4944781a8ed57c6dd"
      define_method(:install) do
        bin.install "loom"
        bin.install "loom-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      Loom installed two binaries:
        - loom       — CLI for ingest, query, lint
        - loom-mcp   — Model Context Protocol stdio server

      Run `loom init` to create ~/.loom/config.toml and your SQLite store.
      The macOS desktop GUI (Loom.app) ships separately on each release page.
    EOS
  end

  test do
    assert_match "loom version", shell_output("#{bin}/loom --version")
  end
end
