# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loom < Formula
  desc "LLM memory: SQLite + BM25 + LLM, no embeddings."
  homepage "https://github.com/MatteoAdamo82/loom"
  version "0.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MatteoAdamo82/loom/releases/download/v0.4.3/loom_0.4.3_macos_x86_64.tar.gz"
      sha256 "64df34d3d049c7d88a117e9f0957db19079e7aa23d7e73611864d6523731def6"

      define_method(:install) do
        bin.install "loom"
        bin.install "loom-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MatteoAdamo82/loom/releases/download/v0.4.3/loom_0.4.3_macos_arm64.tar.gz"
      sha256 "7f3003650cfb329bc3c8ff7d79ff28b0ff5e3935e7043f010d0bb7fe93eacd91"

      define_method(:install) do
        bin.install "loom"
        bin.install "loom-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MatteoAdamo82/loom/releases/download/v0.4.3/loom_0.4.3_linux_x86_64.tar.gz"
      sha256 "4b921768ce6dfdc951f419a86eb1552b96482e75bdef82e4156d873a2c7e03aa"
      define_method(:install) do
        bin.install "loom"
        bin.install "loom-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MatteoAdamo82/loom/releases/download/v0.4.3/loom_0.4.3_linux_arm64.tar.gz"
      sha256 "50594b0a3d0ff82fed00357d5dc95bf95fb4b9a54ba81327cbecc000cc07a457"
      define_method(:install) do
        bin.install "loom"
        bin.install "loom-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      Loom installed two binaries:
        - loom       — CLI for ingest, query, lint
        - loom-mcp   — Model Context Protocol stdio server

      Run `loom init` to create ~/.loom/config.toml and your SQLite store.
      The macOS desktop GUI (Loom.app) ships separately on each release page.
    EOS
  end

  test do
    assert_match "loom version", shell_output("#{bin}/loom --version")
  end
end
