# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loom < Formula
  desc "LLM memory: SQLite + BM25 + LLM, no embeddings."
  homepage "https://github.com/MatteoAdamo82/loom"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MatteoAdamo82/loom/releases/download/v0.4.1/loom_0.4.1_macos_x86_64.tar.gz"
      sha256 "bd45d829b9ac5332ba561d6be3c5ff96677edc629153d3c4ddbac0c993fa70e4"

      define_method(:install) do
        bin.install "loom"
        bin.install "loom-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MatteoAdamo82/loom/releases/download/v0.4.1/loom_0.4.1_macos_arm64.tar.gz"
      sha256 "845ca6644c17f00646e4cd04849263d0a0e71b9d58143ef2dbe1c7aa1a4109f0"

      define_method(:install) do
        bin.install "loom"
        bin.install "loom-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MatteoAdamo82/loom/releases/download/v0.4.1/loom_0.4.1_linux_x86_64.tar.gz"
      sha256 "0d8753b2a9b8b0d4b884529b15344c95cfa10e606de6f34468489d9250c9f279"
      define_method(:install) do
        bin.install "loom"
        bin.install "loom-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MatteoAdamo82/loom/releases/download/v0.4.1/loom_0.4.1_linux_arm64.tar.gz"
      sha256 "789db9d0f5fc4e7bfbf222bfe06e6ad8df4ec5ef13bc09390cab6855aaf64ede"
      define_method(:install) do
        bin.install "loom"
        bin.install "loom-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      Loom installed two binaries:
        - loom       — CLI for ingest, query, lint
        - loom-mcp   — Model Context Protocol stdio server

      Run `loom init` to create ~/.loom/config.toml and your SQLite store.
      The macOS desktop GUI (Loom.app) ships separately on each release page.
    EOS
  end

  test do
    assert_match "loom version", shell_output("#{bin}/loom --version")
  end
end
